GET http://localhost:444/api/ausencias/getAusencias HTTP/1.1

###

POST http://localhost:444/api/ausencias/insertAusencia  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "9fab6b40-94f2-4532-a489-3a01f5af3ca6",
        "justificadas": 1,
        "injustificadas": 1

}

###

PUT http://localhost:444/api/ausencias/updateAusencia/baa10d8b-45a3-4ca0-8cd7-6f592934f5cb  HTTP/1.1
content-type: application/json

{

        "idCursoMatriculado": "9fab6b40-94f2-4532-a489-3a01f5af3ca6",
        "justificadas": 2,
        "injustificadas": 2

}

###

DELETE http://localhost:444/api/ausencias/deleteAusencia/e195453e-30d3-4674-87f3-7742b0875f4b HTTP/1.1
