GET http://localhost:444/api/ausencias/getAusencias/322c7db4-5c86-41c3-8876-9c6e80fa92c5 HTTP/1.1

###

POST http://localhost:444/api/ausencias/insertAusencia  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "d639384d-e31b-4138-ad29-6b7f7450f218",
        "justificadas": 4,
        "injustificadas": 4

}

###

PUT http://localhost:444/api/ausencias/updateAusencia/1fc7d8c4-85a5-43e4-82aa-b5a703ef66b1  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "d74dd718-1691-4257-a539-fd95d6f9efa9",
        "justificadas": 2,
        "injustificadas": 2
}

###

DELETE http://localhost:444/api/ausencias/deleteAusencia/e195453e-30d3-4674-87f3-7742b0875f4b HTTP/1.1
