GET http://localhost:444/api/calificaciones/getCalificaciones HTTP/1.1

###

POST http://localhost:444/api/calificaciones/insertCalificacion  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "9fab6b40-94f2-4532-a489-3a01f5af3ca6",
        "nota": "75",
        "estado": "Aprobado"

}

###

PUT http://localhost:444/api/calificaciones/updateCalificacion/6fa84039-fb1d-432e-bfd0-baa2b967dbce  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "9fab6b40-94f2-4532-a489-3a01f5af3ca6",
        "nota": "65",
        "estado": "Reprobado"

}

###

DELETE http://localhost:444/api/calificaciones/deleteCalificacion/a649dcd3-23e1-4294-95ae-500707f73fd4 HTTP/1.1
