GET http://localhost:444/api/calificaciones/getCalificaciones HTTP/1.1

###

POST http://localhost:444/api/calificaciones/insertCalificacion  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "d74dd718-1691-4257-a539-fd95d6f9efa9",
        "nota": "75",
        "estado": "Aprobado"

}

###

PUT http://localhost:444/api/calificaciones/updateCalificacion/d22eb9d5-ce1d-4497-ae42-81595b80475d  HTTP/1.1
content-type: application/json

{
        "idCursoMatriculado": "d74dd718-1691-4257-a539-fd95d6f9efa9",
        "nota": "65",
        "estado": "Reprobado"

}

###

DELETE http://localhost:444/api/calificaciones/deleteCalificacion/a649dcd3-23e1-4294-95ae-500707f73fd4 HTTP/1.1
