GET http://localhost:444/api/cursos-matriculados/getCursosMatriculados/322c7db4-5c86-41c3-8876-9c6e80fa92c5 HTTP/1.1

###

GET http://localhost:444/api/cursos-matriculados/getCursoMatriculado/6eca30d8-9246-4bdf-b419-3488fe9c98e0 HTTP/1.1

###

POST http://localhost:444/api/cursos-matriculados/insertCursoMatriculado HTTP/1.1
content-type: application/json

{
        "idEstudiante": "1741dc1b-4fc3-497f-aeb1-608f84dcfd53",
        "idCurso": "84a946c9-83b5-417b-9b54-ad1a0f15afd5",
        "idHorario": "",
        "ciclo": "I-2024",
        "nota": "",
        "estado"
}

###

PUT http://localhost:444/api/cursos-matriculados/updateCursoMatriculado/d74dd718-1691-4257-a539-fd95d6f9efa9  HTTP/1.1
content-type: application/json

{
        "idEstudiante": "1741dc1b-4fc3-497f-aeb1-608f84dcfd53",
        "idCurso": "84a946c9-83b5-417b-9b54-ad1a0f15afd5",
        "ciclo": "I-2025"
}

###

DELETE http://localhost:444/api/cursos-matriculados/deleteCursoMatriculado/9ff9beec-8ad4-49d3-be7e-3a630d7eea7c HTTP/1.1
