GET http://localhost:444/api/profesores/getProfesores HTTP/1.1

###

POST http://localhost:444/api/profesores/insertProfesor  HTTP/1.1
content-type: application/json

{
    "nombre": "Wilber Recinos"
}

###

PUT http://localhost:444/api/profesores/updateProfesor/ed51ee37-6d6a-43eb-93fc-06043f82d91d  HTTP/1.1
content-type: application/json

{
    "nombre": "Daniel Chong"
}

###

DELETE http://localhost:444/api/profesores/deleteProfesor/6fa99cab-1628-4f61-8780-110546904a94 HTTP/1.1
